//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddMovy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddMovy()
        {
            this.Seatbookings = new HashSet<Seatbooking>();
        }
    
        public int Movieid { get; set; }
        public int Memberid { get; set; }
        public string Moviename { get; set; }
        public string Movieimage { get; set; }
        public string Genre { get; set; }
        public string Language { get; set; }
        public System.DateTime Releasedate { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public System.DateTime Createdon { get; set; }
        public string Createdby { get; set; }
        public System.DateTime Updatedon { get; set; }
        public string Updatedby { get; set; }
    
        public virtual Membership Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seatbooking> Seatbookings { get; set; }
    }
}
