//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactdetail
    {
        public int Contactid { get; set; }
        public int Memberid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime Dateofbirth { get; set; }
        public string Phonenumber { get; set; }
        public string Email { get; set; }
        public System.DateTime Createdon { get; set; }
        public string Createdby { get; set; }
        public System.DateTime Updatedon { get; set; }
        public string Updatedy { get; set; }
    
        public virtual Membership Membership { get; set; }
    }
}
