//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviebookingEntities : DbContext
    {
        public MoviebookingEntities()
            : base("name=MoviebookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddMovy> AddMovies { get; set; }
        public virtual DbSet<Contactdetail> Contactdetails { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Seatbooking> Seatbookings { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
    }
}
