//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seatbooking
    {
        public int Bookid { get; set; }
        public int Movieid { get; set; }
        public int Memberid { get; set; }
        public string Screen { get; set; }
        public System.DateTime Moviedate { get; set; }
        public System.TimeSpan Movietime { get; set; }
        public int Seatid { get; set; }
        public int Ticketprice { get; set; }
        public int Paymentid { get; set; }
    
        public virtual AddMovy AddMovy { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
